//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExportMilsTableLive
    {
        public int Trade_YEAR_ID { get; set; }
        public Nullable<int> Trade_Year { get; set; }
        public Nullable<int> EU_Total { get; set; }
        public Nullable<int> Asia_Oceania { get; set; }
        public Nullable<int> Eastern_Europe { get; set; }
        public Nullable<int> Latin_America { get; set; }
        public Nullable<int> Middle_East_N_Africa { get; set; }
        public Nullable<int> N_America { get; set; }
        public Nullable<int> Southern_Africa { get; set; }
        public Nullable<int> Western_Europe { get; set; }
        public Nullable<int> Non_EU_Eotal { get; set; }
        public Nullable<int> Grand_Total { get; set; }
    }
}
