//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FarmCurrentConsumptionLive
    {
        public int Farm_Record_ID { get; set; }
        public Nullable<int> Farming_Year { get; set; }
        public Nullable<int> IC_Seeds { get; set; }
        public Nullable<int> IC_Energy { get; set; }
        public Nullable<int> IC_Electricity_and_Fuels_for_Heating { get; set; }
        public Nullable<int> IC_Motor_and_Machinery_Fuels { get; set; }
        public Nullable<int> IC_Fertilisers { get; set; }
        public Nullable<int> IC_Plant_Protection_Products { get; set; }
        public Nullable<int> IC_Veterinary_Expenses { get; set; }
        public Nullable<int> IC_Animal_Feed { get; set; }
        public Nullable<int> IC_Compounds { get; set; }
        public Nullable<int> IC_Straights { get; set; }
        public Nullable<int> IC_Feed_Produced_and_used_on_Farm_or_Purchased_from_other_farms { get; set; }
        public Nullable<int> IC_Total_Maintenance { get; set; }
        public Nullable<int> IC_Materials { get; set; }
        public Nullable<int> IC_Buildings { get; set; }
        public Nullable<int> IC_Agricultural_Services { get; set; }
        public Nullable<int> IC_FISIM { get; set; }
        public Nullable<int> IC_Other_Goods_and_Services { get; set; }
        public Nullable<int> IC_Total_Consumption_of_Fixed_Capital { get; set; }
        public Nullable<int> IC_Equipment { get; set; }
        public Nullable<int> IC_Buildings_Tax { get; set; }
        public Nullable<int> IC_Livestock { get; set; }
        public Nullable<int> IC_Cattle { get; set; }
        public Nullable<int> IC_Pigs { get; set; }
        public Nullable<int> IC_Sheep { get; set; }
        public Nullable<int> IC_Poultry { get; set; }
        public Nullable<int> IC_Other_Taxes_on_Production { get; set; }
        public Nullable<int> IC_Other_Subsidies_on_Production { get; set; }
        public Nullable<int> IC_Compensation_of_Employees { get; set; }
        public Nullable<int> IC_Rent { get; set; }
        public Nullable<int> IC_Interest { get; set; }
    }
}
