//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FarmRealProductionLive
    {
        public int Farm_Record_ID { get; set; }
        public Nullable<int> Farming_Year { get; set; }
        public Nullable<int> Output_of_Cereals { get; set; }
        public Nullable<int> Wheat { get; set; }
        public Nullable<int> Barley { get; set; }
        public Nullable<int> Oats { get; set; }
        public Nullable<int> Output_of_Industrial_Crops { get; set; }
        public Nullable<int> Oilseed_Rape { get; set; }
        public Nullable<int> Protein_Crops { get; set; }
        public Nullable<int> Sugar_Beet { get; set; }
        public Nullable<int> Output_of_Forage_Plants { get; set; }
        public Nullable<int> Output_of_Vegetables_and_Horticultural { get; set; }
        public Nullable<int> Fresh_Vegetables { get; set; }
        public Nullable<int> Plants_and_Flowers { get; set; }
        public Nullable<int> Output_of_Potatoes { get; set; }
        public Nullable<int> Output_of_Fruit { get; set; }
        public Nullable<int> Output_of_Crop_Products { get; set; }
        public Nullable<int> Output_of_Livestock { get; set; }
        public Nullable<int> Primarily_for_meat { get; set; }
        public Nullable<int> Cattle { get; set; }
        public Nullable<int> Pigs { get; set; }
        public Nullable<int> Sheep { get; set; }
        public Nullable<int> Poultry { get; set; }
        public Nullable<int> Gross_Fixed_Captial_Formation { get; set; }
        public Nullable<int> Cattle2 { get; set; }
        public Nullable<int> Pigs2 { get; set; }
        public Nullable<int> Sheep2 { get; set; }
        public Nullable<int> Poultry2 { get; set; }
        public Nullable<int> Output_of_Livestock_Products { get; set; }
        public Nullable<int> Milk { get; set; }
        public Nullable<int> Eggs { get; set; }
        public Nullable<int> Other_Agricultural_Activities { get; set; }
        public Nullable<int> Inseperable_NonAgricultural_Activities { get; set; }
        public Nullable<int> Total_Subsidies_less_taxes { get; set; }
        public Nullable<int> Total_Income { get; set; }
    }
}
