//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LiveDBEntities : DbContext
    {
        public LiveDBEntities()
            : base("name=LiveDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<RainTableLive> RainTableLive { get; set; }
        public virtual DbSet<ExportMilsTableLive> ExportMilsTableLive { get; set; }
        public virtual DbSet<FarmCurrentConsumptionLive> FarmCurrentConsumptionLive { get; set; }
        public virtual DbSet<FarmCurrentProductionLive> FarmCurrentProductionLive { get; set; }
        public virtual DbSet<FarmRealConsumptionLive> FarmRealConsumptionLive { get; set; }
        public virtual DbSet<FarmRealProductionLive> FarmRealProductionLive { get; set; }
    }
}
